[package]
name = "macroquad"
version = "0.3.7"
authors = ["not-fl3 <not.fl3@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
homepage = "https://github.com/not-fl3/macroquad"
repository = "https://github.com/not-fl3/macroquad"
description = """
Simple and easy to use graphics library
"""
readme="README.md"

[features]
audio = ["quad-snd"]
default = ["log-impl", "audio"]
log-impl = ["miniquad/log-impl"]

[package.metadata.android]
assets = "examples/"

[profile.dev.package."*"]
opt-level = 3

[package.metadata.docs.rs]
all-features = true

[dependencies]
miniquad = "0.3.0-alpha.36"
quad-rand = "0.2.1"
glam = {version = "0.14", features = ["scalar-math"] }
image = { version = "0.23.12", default-features = false, features = ["png", "tga"] }
macroquad_macro = { version = "0.1.5", path = "macroquad_macro" }
fontdue = "0.5.0"
bumpalo = "3.4"
backtrace = { version = "0.3.60", optional = true, default-features = false, features = [ "std", "libbacktrace" ] }
quad-snd = { git = "https://github.com/not-fl3/quad-snd.git", rev = "8892248", optional = true }

[dev-dependencies]
macroquad-particles = { path = "./particles" }
macroquad-tiled = { path = "./tiled" }
macroquad-profiler = { path = "./profiler" }
macroquad-platformer = { path = "./physics-platformer" }

# workaround to fix the examples
# this allows to use macroquad-particles in examples without two versions of macroquad
[patch.crates-io]
macroquad = { path = './' }
#quad-snd = {path = '../quad-snd'}

#miniquad = { path = '../miniquad' }
#quad-gl = {path = './quad-gl'}


